name: Deploy to Lambda

on:
    push:
        branches: master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm ci

            - name: Build with deps
              run: npm run build

            - name: Zip
              run: zip -j function.zip ./dist/index.js

            - name: Deploy to AWS
              uses: appleboy/lambda-action@v0.2.0
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  function_name: ZenBotLambda
                  zip_file: ./function.zip
                  handler: index.handler
                  timeout: 100
